<a href="https://colab.research.google.com/github/Katoshy/Data-Analysis-Projects/blob/main/AD_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Підготовка**
Підключення бібліотек та завантаження даних

In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Birthweight.csv')

**Завдання №1**
Виділити один зі стовпців (на вибір) з файлу як об’єкт Series, виділити з
нього підмасив. Задати назви індексів цього об’єкту. Виділити підмасиви
за допомогою прямої та непрямої індексацій.

In [ ]:
mother_age = np.array(data['mage'])
_mother_age = pd.Series(mother_age,index = np.arange(2,2*(data.shape[0]+1),2))
_mother_age

2     20
4     19
6     35
8     20
10    24
12    29
14    24
16    21
18    18
20    20
22    27
24    24
26    31
28    21
30    29
32    28
34    27
36    26
38    19
40    24
42    20
44    22
46    19
48    22
50    20
52    41
54    20
56    32
58    31
60    27
62    30
64    23
66    21
68    28
70    30
72    37
74    26
76    23
78    31
80    27
82    20
84    37
dtype: int64

In [ ]:
print('forward indexing')
print(_mother_age.loc[10:55:3])
print('backward indexing')
print(_mother_age.iloc[14:2:3])

forward indexing
10    24
16    21
22    27
28    21
34    27
40    24
46    19
52    41
dtype: int64
backward indexing
Series([], dtype: int64)

**Завдання №2**
До об’єкту DataFrame, в який записано вміст файлу, додати новий
стовпець, що є результатом операцій над іншими стовпцями. Також
продемонструвати додавання та видалення рядків, видалення стовпців.

In [ ]:
data

,ID,Length,Birthweight,Headcirc,Gestation,smoker,mage,mnocig,mheight,mppwt,fage,fedyrs,fnocig,fheight,lowbwt,mage35
0,1360,56,4.55,34,44,0,20,0,162,57,23,10,35,179,0,0
1,1016,53,4.32,36,40,0,19,0,171,62,19,12,0,183,0,0
2,462,58,4.10,39,41,0,35,0,172,58,31,16,25,185,0,1
3,1187,53,4.07,38,44,0,20,0,174,68,26,14,25,189,0,0
4,553,54,3.94,37,42,0,24,0,175,66,30,12,0,184,0,0
5,1636,51,3.93,38,38,0,29,0,165,61,31,16,0,180,0,0
6,820,52,3.77,34,40,0,24,0,157,50,31,16,0,173,0,0
7,1191,53,3.65,33,42,0,21,0,165,61,21,10,25,185,0,0
8,1081,54,3.63,38,38,0,18,0,172,50,20,12,7,172,0,0
9,822,50,3.42,35,38,0,20,0,157,48,22,14,0,179,0,0
10,1683,53,3.35,33,41,0,27,0,164,62,37,14,0,170,0,0
11,1088,51,3.27,36,40,0,24,0,168,53,29,16,0,181,0,0
12,1107,52,3.23,36,38,0,31,0,164,57,35,16,0,183,0,0
13,755,53,3.20,33,41,0,21,0,155,55,25,14,25,183,0,0
14,1058,53,3.15,34,40,0,29,0,167,60,30,16,25,182,0,0
15,321,48,3.11,33,37,0,28,0,158,54,39,10,0,171,0,0
16,697,48,3.03,35,39,0,27,0,162,62,27,14,0,178,0,0
17,808,48,2.92,33,34,0,26,0,167,64,25,12,25,175,0,0
18,1600,53,2.90,34,39,0,19,0,165,57,23,14,2,193,0,0
19,1313,43,2.65,32,33,0,24,0,149,45,26,16,0,169,1,0
20,792,53,3.64,38,40,1,20,2,170,59,24,12,12,185,0,0
21,1388,51,3.14,33,41,1,22,7,160,53,24,16,12,176,0,0
22,575,50,2.78,30,37,1,19,7,165,60,20,14,0,183,0,0
23,569,50,2.51,35,39,1,22,7,159,52,23,14,25,200,1,0
24,1363,48,2.37,30,37,1,20,7,163,47,20,10,35,185,1,0
25,300,46,2.05,32,35,1,41,7,166,57,37,14,25,173,1,1
26,431,48,1.92,30,33,1,20,7,161,50,20,10,35,180,1,0
27,1764,58,4.57,39,41,1,32,12,173,70,38,14,25,180,0,0
28,532,53,3.59,34,40,1,31,12,163,49,41,12,50,191,0,0
29,752,49,3.32,36,40,1,27,12,152,48,37,12,25,170,0,0
30,1023,52,3.00,35,38,1,30,12,165,64,38,14,50,180,0,0
31,57,51,3.32,38,39,1,23,17,157,48,32,12,25,169,0,0
32,1522,50,2.74,33,39,1,21,17,156,53,24,12,7,179,0,0
33,223,50,3.87,33,45,1,28,25,163,54,30,16,0,183,0,0
34,272,52,3.86,36,39,1,30,25,170,78,40,16,50,178,0,0
35,27,53,3.55,37,41,1,37,25,161,66,46,16,0,175,0,1
36,365,52,3.53,37,40,1,26,25,170,62,30,10,25,181,0,0
37,619,52,3.41,33,39,1,23,25,181,69,23,16,2,181,0,0
38,1369,49,3.18,34,38,1,31,25,162,57,32,16,50,194,0,0
39,1262,53,3.19,34,41,1,27,35,163,51,31,16,25,185,0,0
40,516,47,2.66,33,35,1,20,35,170,57,23,12,50,186,1,0
41,1272,53,2.75,32,40,1,37,50,168,61,31,16,0,173,0,1

In [ ]:
data['%body mass index'] = data['Birthweight']/((data['Length']/100)**2)
data['new']=None
del data['ID']
data

,Length,Birthweight,Headcirc,Gestation,smoker,mage,mnocig,mheight,mppwt,fage,fedyrs,fnocig,fheight,lowbwt,mage35,%body mass index,new
0,56,4.55,34,44,0,20,0,162,57,23,10,35,179,0,0,14.508929,None
1,53,4.32,36,40,0,19,0,171,62,19,12,0,183,0,0,15.379138,None
2,58,4.10,39,41,0,35,0,172,58,31,16,25,185,0,1,12.187872,None
3,53,4.07,38,44,0,20,0,174,68,26,14,25,189,0,0,14.489142,None
4,54,3.94,37,42,0,24,0,175,66,30,12,0,184,0,0,13.511660,None
5,51,3.93,38,38,0,29,0,165,61,31,16,0,180,0,0,15.109573,None
6,52,3.77,34,40,0,24,0,157,50,31,16,0,173,0,0,13.942308,None
7,53,3.65,33,42,0,21,0,165,61,21,10,25,185,0,0,12.993948,None
8,54,3.63,38,38,0,18,0,172,50,20,12,7,172,0,0,12.448560,None
9,50,3.42,35,38,0,20,0,157,48,22,14,0,179,0,0,13.680000,None
10,53,3.35,33,41,0,27,0,164,62,37,14,0,170,0,0,11.925952,None
11,51,3.27,36,40,0,24,0,168,53,29,16,0,181,0,0,12.572088,None
12,52,3.23,36,38,0,31,0,164,57,35,16,0,183,0,0,11.945266,None
13,53,3.20,33,41,0,21,0,155,55,25,14,25,183,0,0,11.391954,None
14,53,3.15,34,40,0,29,0,167,60,30,16,25,182,0,0,11.213955,None
15,48,3.11,33,37,0,28,0,158,54,39,10,0,171,0,0,13.498264,None
16,48,3.03,35,39,0,27,0,162,62,27,14,0,178,0,0,13.151042,None
17,48,2.92,33,34,0,26,0,167,64,25,12,25,175,0,0,12.673611,None
18,53,2.90,34,39,0,19,0,165,57,23,14,2,193,0,0,10.323959,None
19,43,2.65,32,33,0,24,0,149,45,26,16,0,169,1,0,14.332071,None
20,53,3.64,38,40,1,20,2,170,59,24,12,12,185,0,0,12.958348,None
21,51,3.14,33,41,1,22,7,160,53,24,16,12,176,0,0,12.072280,None
22,50,2.78,30,37,1,19,7,165,60,20,14,0,183,0,0,11.120000,None
23,50,2.51,35,39,1,22,7,159,52,23,14,25,200,1,0,10.040000,None
24,48,2.37,30,37,1,20,7,163,47,20,10,35,185,1,0,10.286458,None
25,46,2.05,32,35,1,41,7,166,57,37,14,25,173,1,1,9.688091,None
26,48,1.92,30,33,1,20,7,161,50,20,10,35,180,1,0,8.333333,None
27,58,4.57,39,41,1,32,12,173,70,38,14,25,180,0,0,13.585018,None
28,53,3.59,34,40,1,31,12,163,49,41,12,50,191,0,0,12.780349,None
29,49,3.32,36,40,1,27,12,152,48,37,12,25,170,0,0,13.827572,None
30,52,3.00,35,38,1,30,12,165,64,38,14,50,180,0,0,11.094675,None
31,51,3.32,38,39,1,23,17,157,48,32,12,25,169,0,0,12.764321,None
32,50,2.74,33,39,1,21,17,156,53,24,12,7,179,0,0,10.960000,None
33,50,3.87,33,45,1,28,25,163,54,30,16,0,183,0,0,15.480000,None
34,52,3.86,36,39,1,30,25,170,78,40,16,50,178,0,0,14.275148,None
35,53,3.55,37,41,1,37,25,161,66,46,16,0,175,0,1,12.637949,None
36,52,3.53,37,40,1,26,25,170,62,30,10,25,181,0,0,13.054734,None
37,52,3.41,33,39,1,23,25,181,69,23,16,2,181,0,0,12.610947,None
38,49,3.18,34,38,1,31,25,162,57,32,16,50,194,0,0,13.244481,None
39,53,3.19,34,41,1,27,35,163,51,31,16,25,185,0,0,11.356355,None
40,47,2.66,33,35,1,20,35,170,57,23,12,50,186,1,0,12.041648,None
41,53,2.75,32,40,1,37,50,168,61,31,16,0,173,0,1,9.789961,None

In [ ]:
new_child ={
    'Length':	[1],
    'Birthweight': [1],
    'Headcirc':	[1],
    'Gestation': [1],	
    'smoker': [1],
    'mage':	[1],
    'mnocig': [1],	
    'mheight': [1],	
    'mppwt': [1],
    'fage':	[1],
    'fedyrs':	[1],
    'fnocig':	[1],
    'fheight': [1],
    'lowbwt': [1],
    'mage35':	 [1],
    '%body mass index':	[1],
    'new': [1]
}
ser = pd.DataFrame(data = new_child)
print(ser)
a=pd.concat([data,ser],ignore_index=True)
a.drop(columns = 'new',inplace = True)
a

   Length  Birthweight  Headcirc  Gestation  smoker  mage  mnocig  mheight  \
0       1            1         1          1       1     1       1        1

   mppwt  fage  fedyrs  fnocig  fheight  lowbwt  mage35  %body mass index  new
0      1     1       1       1        1       1       1                 1    1

,Length,Birthweight,Headcirc,Gestation,smoker,mage,mnocig,mheight,mppwt,fage,fedyrs,fnocig,fheight,lowbwt,mage35,%body mass index
0,56,4.55,34,44,0,20,0,162,57,23,10,35,179,0,0,14.508929
1,53,4.32,36,40,0,19,0,171,62,19,12,0,183,0,0,15.379138
2,58,4.10,39,41,0,35,0,172,58,31,16,25,185,0,1,12.187872
3,53,4.07,38,44,0,20,0,174,68,26,14,25,189,0,0,14.489142
4,54,3.94,37,42,0,24,0,175,66,30,12,0,184,0,0,13.511660
5,51,3.93,38,38,0,29,0,165,61,31,16,0,180,0,0,15.109573
6,52,3.77,34,40,0,24,0,157,50,31,16,0,173,0,0,13.942308
7,53,3.65,33,42,0,21,0,165,61,21,10,25,185,0,0,12.993948
8,54,3.63,38,38,0,18,0,172,50,20,12,7,172,0,0,12.448560
9,50,3.42,35,38,0,20,0,157,48,22,14,0,179,0,0,13.680000
10,53,3.35,33,41,0,27,0,164,62,37,14,0,170,0,0,11.925952
11,51,3.27,36,40,0,24,0,168,53,29,16,0,181,0,0,12.572088
12,52,3.23,36,38,0,31,0,164,57,35,16,0,183,0,0,11.945266
13,53,3.20,33,41,0,21,0,155,55,25,14,25,183,0,0,11.391954
14,53,3.15,34,40,0,29,0,167,60,30,16,25,182,0,0,11.213955
15,48,3.11,33,37,0,28,0,158,54,39,10,0,171,0,0,13.498264
16,48,3.03,35,39,0,27,0,162,62,27,14,0,178,0,0,13.151042
17,48,2.92,33,34,0,26,0,167,64,25,12,25,175,0,0,12.673611
18,53,2.90,34,39,0,19,0,165,57,23,14,2,193,0,0,10.323959
19,43,2.65,32,33,0,24,0,149,45,26,16,0,169,1,0,14.332071
20,53,3.64,38,40,1,20,2,170,59,24,12,12,185,0,0,12.958348
21,51,3.14,33,41,1,22,7,160,53,24,16,12,176,0,0,12.072280
22,50,2.78,30,37,1,19,7,165,60,20,14,0,183,0,0,11.120000
23,50,2.51,35,39,1,22,7,159,52,23,14,25,200,1,0,10.040000
24,48,2.37,30,37,1,20,7,163,47,20,10,35,185,1,0,10.286458
25,46,2.05,32,35,1,41,7,166,57,37,14,25,173,1,1,9.688091
26,48,1.92,30,33,1,20,7,161,50,20,10,35,180,1,0,8.333333
27,58,4.57,39,41,1,32,12,173,70,38,14,25,180,0,0,13.585018
28,53,3.59,34,40,1,31,12,163,49,41,12,50,191,0,0,12.780349
29,49,3.32,36,40,1,27,12,152,48,37,12,25,170,0,0,13.827572
30,52,3.00,35,38,1,30,12,165,64,38,14,50,180,0,0,11.094675
31,51,3.32,38,39,1,23,17,157,48,32,12,25,169,0,0,12.764321
32,50,2.74,33,39,1,21,17,156,53,24,12,7,179,0,0,10.960000
33,50,3.87,33,45,1,28,25,163,54,30,16,0,183,0,0,15.480000
34,52,3.86,36,39,1,30,25,170,78,40,16,50,178,0,0,14.275148
35,53,3.55,37,41,1,37,25,161,66,46,16,0,175,0,1,12.637949
36,52,3.53,37,40,1,26,25,170,62,30,10,25,181,0,0,13.054734
37,52,3.41,33,39,1,23,25,181,69,23,16,2,181,0,0,12.610947
38,49,3.18,34,38,1,31,25,162,57,32,16,50,194,0,0,13.244481
39,53,3.19,34,41,1,27,35,163,51,31,16,25,185,0,0,11.356355
40,47,2.66,33,35,1,20,35,170,57,23,12,50,186,1,0,12.041648
41,53,2.75,32,40,1,37,50,168,61,31,16,0,173,0,1,9.789961
42,1,1.00,1,1,1,1,1,1,1,1,1,1,1,1,1,1.000000

**Завдання №3**
Встановити один зі стовпців індексом. Визначити основні статистичні
характеристики та типи даних всіх стовпців. Змінити тип даних для
одного з стовпців. Згрупувати дані за одним зі стовпців, застосувати
кілька агрегуючих функцій, виділити підмасив за певними ознаками.

In [ ]:
name  = ['vmv','cio','kmm','rdj','awe','qwe','tyr','ert','qwr','asd','adf','fda','khg','uhb','dug','qwe','dfh','xmv','yoi','vch','ciu','xvy','yme','zqe','vnu','don','inb','xry','cub','lug','vmv','cio','kmm','rdj','awe','qwe','tyr','ert','qwr','asd','adf','fda']
data['Name'] = name
data.set_index("Name")

,Length,Birthweight,Headcirc,Gestation,smoker,mage,mnocig,mheight,mppwt,fage,fedyrs,fnocig,fheight,lowbwt,mage35,%body mass index,new
Name,,,,,,,,,,,,,,,,,
vmv,56,4.55,34,44,0,20,0,162,57,23,10,35,179,0,0,14.508929,None
cio,53,4.32,36,40,0,19,0,171,62,19,12,0,183,0,0,15.379138,None
kmm,58,4.10,39,41,0,35,0,172,58,31,16,25,185,0,1,12.187872,None
rdj,53,4.07,38,44,0,20,0,174,68,26,14,25,189,0,0,14.489142,None
awe,54,3.94,37,42,0,24,0,175,66,30,12,0,184,0,0,13.511660,None
qwe,51,3.93,38,38,0,29,0,165,61,31,16,0,180,0,0,15.109573,None
tyr,52,3.77,34,40,0,24,0,157,50,31,16,0,173,0,0,13.942308,None
ert,53,3.65,33,42,0,21,0,165,61,21,10,25,185,0,0,12.993948,None
qwr,54,3.63,38,38,0,18,0,172,50,20,12,7,172,0,0,12.448560,None
asd,50,3.42,35,38,0,20,0,157,48,22,14,0,179,0,0,13.680000,None
adf,53,3.35,33,41,0,27,0,164,62,37,14,0,170,0,0,11.925952,None
fda,51,3.27,36,40,0,24,0,168,53,29,16,0,181,0,0,12.572088,None
khg,52,3.23,36,38,0,31,0,164,57,35,16,0,183,0,0,11.945266,None
uhb,53,3.20,33,41,0,21,0,155,55,25,14,25,183,0,0,11.391954,None
dug,53,3.15,34,40,0,29,0,167,60,30,16,25,182,0,0,11.213955,None
qwe,48,3.11,33,37,0,28,0,158,54,39,10,0,171,0,0,13.498264,None
dfh,48,3.03,35,39,0,27,0,162,62,27,14,0,178,0,0,13.151042,None
xmv,48,2.92,33,34,0,26,0,167,64,25,12,25,175,0,0,12.673611,None
yoi,53,2.90,34,39,0,19,0,165,57,23,14,2,193,0,0,10.323959,None
vch,43,2.65,32,33,0,24,0,149,45,26,16,0,169,1,0,14.332071,None
ciu,53,3.64,38,40,1,20,2,170,59,24,12,12,185,0,0,12.958348,None
xvy,51,3.14,33,41,1,22,7,160,53,24,16,12,176,0,0,12.072280,None
yme,50,2.78,30,37,1,19,7,165,60,20,14,0,183,0,0,11.120000,None
zqe,50,2.51,35,39,1,22,7,159,52,23,14,25,200,1,0,10.040000,None
vnu,48,2.37,30,37,1,20,7,163,47,20,10,35,185,1,0,10.286458,None
don,46,2.05,32,35,1,41,7,166,57,37,14,25,173,1,1,9.688091,None
inb,48,1.92,30,33,1,20,7,161,50,20,10,35,180,1,0,8.333333,None
xry,58,4.57,39,41,1,32,12,173,70,38,14,25,180,0,0,13.585018,None
cub,53,3.59,34,40,1,31,12,163,49,41,12,50,191,0,0,12.780349,None
lug,49,3.32,36,40,1,27,12,152,48,37,12,25,170,0,0,13.827572,None
vmv,52,3.00,35,38,1,30,12,165,64,38,14,50,180,0,0,11.094675,None
cio,51,3.32,38,39,1,23,17,157,48,32,12,25,169,0,0,12.764321,None
kmm,50,2.74,33,39,1,21,17,156,53,24,12,7,179,0,0,10.960000,None
rdj,50,3.87,33,45,1,28,25,163,54,30,16,0,183,0,0,15.480000,None
awe,52,3.86,36,39,1,30,25,170,78,40,16,50,178,0,0,14.275148,None
qwe,53,3.55,37,41,1,37,25,161,66,46,16,0,175,0,1,12.637949,None
tyr,52,3.53,37,40,1,26,25,170,62,30,10,25,181,0,0,13.054734,None
ert,52,3.41,33,39,1,23,25,181,69,23,16,2,181,0,0,12.610947,None
qwr,49,3.18,34,38,1,31,25,162,57,32,16,50,194,0,0,13.244481,None
asd,53,3.19,34,41,1,27,35,163,51,31,16,25,185,0,0,11.356355,None
adf,47,2.66,33,35,1,20,35,170,57,23,12,50,186,1,0,12.041648,None
fda,53,2.75,32,40,1,37,50,168,61,31,16,0,173,0,1,9.789961,None

In [ ]:
del data['new']
#del data['%body mass index']
a=data.mean(axis=0)
b=data.median(axis=0)
c=data.mode(axis='rows')
x = pd.DataFrame({'mean':a,'median':b})
print(x)

                        mean     median
Length             51.333333   52.00000
Birthweight         3.312857    3.29500
Headcirc           34.595238   34.00000
Gestation          39.190476   39.50000
smoker              0.523810    1.00000
mage               25.547619   24.00000
mnocig              9.428571    4.50000
mheight           164.452381  164.50000
mppwt              57.500000   57.00000
fage               28.904762   29.50000
fedyrs             13.666667   14.00000
fnocig             17.190476   18.50000
fheight           180.500000  180.50000
lowbwt              0.142857    0.00000
mage35              0.095238    0.00000
%body mass index   12.506690   12.65578

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.

In [ ]:
print(data.dtypes)
data['mage35']=data['mage35'].astype('bool')
print(data.dtypes)

Length                int64
Birthweight         float64
Headcirc              int64
Gestation             int64
smoker                int64
mage                  int64
mnocig                int64
mheight               int64
mppwt                 int64
fage                  int64
fedyrs                int64
fnocig                int64
fheight               int64
lowbwt                int64
mage35                int64
%body mass index    float64
Name                 object
dtype: object
Length                int64
Birthweight         float64
Headcirc              int64
Gestation             int64
smoker                int64
mage                  int64
mnocig                int64
mheight               int64
mppwt                 int64
fage                  int64
fedyrs                int64
fnocig                int64
fheight               int64
lowbwt                int64
mage35                 bool
%body mass index    float64
Name                 object
dtype: object

In [ ]:
data[(data.mage>20)&(data.mage<30)]

,Length,Birthweight,Headcirc,Gestation,smoker,mage,mnocig,mheight,mppwt,fage,fedyrs,fnocig,fheight,lowbwt,mage35,%body mass index,Name
4,54,3.94,37,42,0,24,0,175,66,30,12,0,184,0,False,13.511660,awe
5,51,3.93,38,38,0,29,0,165,61,31,16,0,180,0,False,15.109573,qwe
6,52,3.77,34,40,0,24,0,157,50,31,16,0,173,0,False,13.942308,tyr
7,53,3.65,33,42,0,21,0,165,61,21,10,25,185,0,False,12.993948,ert
10,53,3.35,33,41,0,27,0,164,62,37,14,0,170,0,False,11.925952,adf
11,51,3.27,36,40,0,24,0,168,53,29,16,0,181,0,False,12.572088,fda
13,53,3.20,33,41,0,21,0,155,55,25,14,25,183,0,False,11.391954,uhb
14,53,3.15,34,40,0,29,0,167,60,30,16,25,182,0,False,11.213955,dug
15,48,3.11,33,37,0,28,0,158,54,39,10,0,171,0,False,13.498264,qwe
16,48,3.03,35,39,0,27,0,162,62,27,14,0,178,0,False,13.151042,dfh
17,48,2.92,33,34,0,26,0,167,64,25,12,25,175,0,False,12.673611,xmv
19,43,2.65,32,33,0,24,0,149,45,26,16,0,169,1,False,14.332071,vch
21,51,3.14,33,41,1,22,7,160,53,24,16,12,176,0,False,12.072280,xvy
23,50,2.51,35,39,1,22,7,159,52,23,14,25,200,1,False,10.040000,zqe
29,49,3.32,36,40,1,27,12,152,48,37,12,25,170,0,False,13.827572,lug
31,51,3.32,38,39,1,23,17,157,48,32,12,25,169,0,False,12.764321,cio
32,50,2.74,33,39,1,21,17,156,53,24,12,7,179,0,False,10.960000,kmm
33,50,3.87,33,45,1,28,25,163,54,30,16,0,183,0,False,15.480000,rdj
36,52,3.53,37,40,1,26,25,170,62,30,10,25,181,0,False,13.054734,tyr
37,52,3.41,33,39,1,23,25,181,69,23,16,2,181,0,False,12.610947,ert
39,53,3.19,34,41,1,27,35,163,51,31,16,25,185,0,False,11.356355,asd

In [ ]:
data.groupby('smoker')['Birthweight'].agg([sum,np.mean,np.min,np.max])

          sum      mean  amin  amax
smoker
0       70.19  3.509500  2.65  4.55
1       68.95  3.134091  1.92  4.57

**Завдання №4**
Створити декілька власних об’єктів DataFrame за такою ж тематикою, що
й файл. Наприклад, якщо тема файлу – жаби, можна створити об’єкти,
що містять розміри жаб, вагу, стать, кількість особин в популяції і т.д.
Використати описані в теоретичних відомостях параметри методів merge
та concat для різних видів злиття та об’єднання даних цих об’єктів.

In [ ]:
dateofBirth = pd.DataFrame({'Name': ['vmv','kmm','cio'] , 'DateOfBirth': ["23.07.2001","14.05.2004","22.04.2002"]})
print(dateofBirth)
dataBirth = pd.merge(dateofBirth, data, left_on='Name', right_on='Name')

  Name DateOfBirth
0  vmv  23.07.2001
1  kmm  14.05.2004
2  cio  22.04.2002

In [ ]:
dataBirth

,Name,DateOfBirth,Length,Birthweight,Headcirc,Gestation,smoker,mage,mnocig,mheight,mppwt,fage,fedyrs,fnocig,fheight,lowbwt,mage35,%body mass index
0,vmv,23.07.2001,56,4.55,34,44,0,20,0,162,57,23,10,35,179,0,False,14.508929
1,vmv,23.07.2001,52,3.00,35,38,1,30,12,165,64,38,14,50,180,0,False,11.094675
2,kmm,14.05.2004,58,4.10,39,41,0,35,0,172,58,31,16,25,185,0,True,12.187872
3,kmm,14.05.2004,50,2.74,33,39,1,21,17,156,53,24,12,7,179,0,False,10.960000
4,cio,22.04.2002,53,4.32,36,40,0,19,0,171,62,19,12,0,183,0,False,15.379138
5,cio,22.04.2002,51,3.32,38,39,1,23,17,157,48,32,12,25,169,0,False,12.764321

In [ ]:
scipy.stats.pearsonr()

NameError: ignored